# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GVENCK
email: gvenck@usp.br
description: > # this means to ignore newlines until "baseurl:"
  Copyright© 2020. All rights reserved.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gvenck.github.io" # the base hostname & protocol for your site
twitter_username: GVENCK_ESALQ
github_username:  gvenck

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
